--<ScriptOptions statementTerminator=";"/>

CREATE TABLE student (
	ID BIGINT UNSIGNED NOT NULL,
	FIRST_NAME VARCHAR(45) NOT NULL,
	MIDDLE_NAME VARCHAR(45),
	LAST_NAME VARCHAR(45) NOT NULL,
	GENDER VARCHAR(6) NOT NULL,
	DATE_OF_BIRTH DATE NOT NULL,
	BRANCH VARCHAR(45) NOT NULL,
	ADDMISSION_YEAR VARCHAR(4) NOT NULL,
    CHALLAN_NO VARCHAR(45) NOT NULL,
    EMAIL_ID VARCHAR(45) NOT NULL,
	MOBILE_NO BIGINT UNSIGNED NOT NULL,
    UNIQUE_ID VARCHAR(45) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE branch (
	ID INTEGER UNSIGNED NOT NULL,
	BRANCH_NAME VARCHAR(45) NOT NULL,
	DURATION VARCHAR(2) NOT NULL,
	NUMBER_OF_SEMESTER VARCHAR(5) NOT NULL,
	PRIMARY KEY (ID)
);

